apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-nodeport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-nodeport
  template:
    metadata:
      labels:
        app: nginx-nodeport
    spec:
      containers:
      - name: nginx
        image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
spec:
  selector:
    app: nginx-nodeport
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007  # You can specify a custom node port in the range 30000-32767
  type: NodePort

