version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - "8083:80"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
