---
- name: Install Java (required by SonarQube)
  apt:
    name: openjdk-11-jdk
    state: present
  become: true

- name: Download SonarQube
  get_url:
    url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.9.1.69595.zip
    dest: /tmp/sonarqube.zip
  become: true

- name: Install unzip
  apt:
    name: unzip
    state: present
  become: true

- name: Extract SonarQube
  unarchive:
    src: /tmp/sonarqube.zip
    dest: /opt
    remote_src: yes
  become: true

- name: Get SonarQube extracted directory name
  shell: ls -d /opt/sonarqube-*
  register: extracted_dir
  become: true

- name: Rename SonarQube directory
  command:
    cmd: mv "{{ extracted_dir.stdout }}" /opt/sonarqube
  become: true

- name: Create SonarQube user
  user:
    name: sonarqube
    shell: /bin/bash
    system: yes
  become: true

- name: Set ownership for SonarQube directory
  file:
    path: /opt/sonarqube
    state: directory
    owner: sonarqube
    group: sonarqube
    recurse: yes
  become: true

- name: Update sonar.properties for port and host
  lineinfile:
    path: /opt/sonarqube/conf/sonar.properties
    regexp: '^#?sonar.web.host='
    line: 'sonar.web.host=0.0.0.0'
  become: true

- name: Update sonar.properties for web port
  lineinfile:
    path: /opt/sonarqube/conf/sonar.properties
    regexp: '^#?sonar.web.port='
    line: 'sonar.web.port=9000'
  become: true

- name: Configure JVM options for Elasticsearch memory
  lineinfile:
    path: /opt/sonarqube/conf/sonar.properties
    regexp: '^#?sonar.search.javaOpts='
    line: 'sonar.search.javaOpts=-Xms512m -Xmx512m'
  become: true

- name: Configure SonarQube systemd service
  template:
    src: sonarqube.service.j2
    dest: /etc/systemd/system/sonarqube.service
  become: true

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  become: true

- name: Reset systemd failed state (if any)
  command: systemctl reset-failed
  become: true

- name: Start and Enable SonarQube service
  systemd:
    name: sonarqube
    state: started
    enabled: yes
  become: true
