# roles/sonarqube/tasks/main.yml
---
- name: Install Java (required by SonarQube)
  apt:
    name: openjdk-11-jdk
    state: present
  become: true

- name: Download SonarQube
  get_url:
    url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.9.1.69595.zip
    dest: /tmp/sonarqube.zip

- name: Install unzip
  apt:
    name: unzip
    state: present
  become: true

- name: Extract SonarQube
  unarchive:
    src: /tmp/sonarqube.zip
    dest: /opt
    remote_src: yes

- name: Get SonarQube extracted directory name
  shell: ls -d /opt/sonarqube-*
  register: extracted_dir

- name: Rename SonarQube directory
  command:
    cmd: mv "{{ extracted_dir.stdout }}" /opt/sonarqube
  become: true

- name: Configure SonarQube systemd service
  template:
    src: sonarqube.service.j2
    dest: /etc/systemd/system/sonarqube.service
  become: true

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  become: true

- name: Start and Enable SonarQube service
  systemd:
    name: sonarqube
    state: started
    enabled: yes
  become: true
